### ISSUE TITLE
stageの作り方で、プレイヤーが見えない

### ISSUE THREAD

**Issue by riteiiku** [takasumiu/HackTheWorld#112]
3. 左下のボタンを押すと、～
のところで、
ボタンを押してもプレイヤーが見えない。

でも、プレイヤーの位置に敵を置いたらゲームが終わったので
存在はするけど、見えないだけだと思う。

**Comment by takasumiu** [comment]
調査中
GameScene開始時にプレイヤー即死するのもこれが原因ぽいな
