### ISSUE TITLE
マウスの入力をとれるように

### ISSUE THREAD

**Issue by takasumiu** [takasumiu/HackTheWorld#29]
マウスの入力を取得する側に、何が必要になりそうかを考えながら実装してもらえるとありがたい。
具体的な使用シーンを思い浮かべながらやるといいと思う。
ブロックをドラッグアンドドロップするとか

**Comment by yamadayamadayamadayamada** [comment]
途中までやりました
ドラッグするとDraggingがtrueになって
座標をリストに保存して
ドロップするとDraggingがfalseになります
