### ISSUE TITLE
velocityの値をfpsの値を使用して秒速にする

### ISSUE THREAD

**Issue by YudaiH** [takasumiu/HackTheWorld#31]
秒速でなくてもいい。マジックナンバー10があるのはよくないのでは(GameObject.cs)

**Comment by YudaiH** [comment]
秒速にしたいなら、10をFpsに書き換えればよいと気づきました。
だからScaleはFpsの倍数のほうがいいですね。60にしませんか？
とりあえず放っておきます。

**Comment by takasumiu** [comment]
近いうちに対応します

**Comment by takasumiu** [comment]
@YudaiH 
やりました。
確認して大丈夫そうだったらCloseしてもらえると

**Comment by takasumiu** [comment]
Completed
