### ISSUE TITLE
Windowのサイズ

### ISSUE THREAD

**Issue by YudaiH** [takasumiu/HackTheWorld#33]
Formの大きさを変えても等倍に拡縮されるようにしたい。

**Comment by takasumiu** [comment]
これはそのうち

**Comment by takasumiu** [comment]
@yamada に調査をお願いしたい

**Comment by takasumiu** [comment]
もしやるなら、Window を自由に拡大縮小させるという感じよりは、ウインドウモード・フルスクリーンモードで選べる感じがいいと思う。
フルスクリーンモードは、ただウィンドウサイズを変更するだけじゃなくて、タスクバー含めたウィンドウ全体に表示されるやつ。

**Comment by yamatekazumasa** [comment]
- フルスクリーンモード
- ウィンドウの内側にステージの画面と操作ボタンを置く
  - 内側のステージ画面の大きさは3:4

**Comment by takasumiu** [comment]
#51 にて対応されたので
