### ISSUE TITLE
プルリクのテスト(三橋)

### ISSUE THREAD

**Issue by takasumiu** [takasumiu/HackTheWorld#4]
それぞれ適当にファイルを更新してプルリクを送ってみてください。

**Comment by takasumiu** [comment]
コミットメッセージやPull request内で #○○ という形で言及すると上みたいにログが残って分かりやすい

**Comment by 441121111** [comment]
わかった。

2016年3月19日土曜日、高澄佑<notifications@github.com>さんは書きました:

> コミットメッセージやPull request内で #○○ という形で言及すると上みたいにログが残って分かりやすい
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/takasumiu/HackTheWorld/issues/4#issuecomment-198701021>
>


-- 
早稲田大学 先進理工学部
電気・情報生命工学科
井上真郷研究室 学部3年
三橋 響

hbkmths@gmail.com
