### ISSUE TITLE
キー入力時たまにエラー吐いて止まる

### ISSUE THREAD

**Issue by 441121111** [takasumiu/HackTheWorld#42]
Input.csの
public static void Update(LinkedList<Keys> pressedKeys)の中の
foreach (var key in pressedKeys)
でハンドルされませんでしたされる

こまったな

**Comment by takasumiu** [comment]
エラーコードコピペかスクショしてくれると助かる

**Comment by YudaiH** [comment]
▲ InvalidOperationException はハンドルされませんでした。
型 'System.InvalidOperationException' のハンドルされていない例外が System.dll で発生しました
追加情報:列挙子がインスタンス化されてから、コレクションが変更されました。

とのことです。

**Comment by takasumiu** [comment]
キーボード入力の取得方法を変えたので解決したはず。
