### ISSUE TITLE
Adjustの端数処理の誤差

### ISSUE THREAD

**Issue by YudaiH** [takasumiu/HackTheWorld#50]
GameObject.csのAdjust()での問題。
 this.Y -= MaxY - obj.MinY;
のようにfloat同士の計算をしているためか、正確に差が0で乗っている状態にはならない。(浮いていることがある。)
乗り判定で誤判するので、修正が必要です。

this.MaxY == obj.MinY　になるとベスト。
無理ならば、0=< this.MaxY - obj.MinY < 1.0　が保証されるようにしたい。

**Comment by takasumiu** [comment]
移動してブロックにのめり込むのは基本的にオブジェクトの速度を勘定に入れてないのが原因だからAdjustの判定部分をobj.VX,obj.VYを使って作り直したらいいと思う

**Comment by takasumiu** [comment]
スレチだったわ

**Comment by YudaiH** [comment]
仮で直しました。
MinXとかは出力や保有値がfloatなのに入力がintだけだから、誤差はまぬかれないので
this.MaxY == obj.MinY　になるのはあきらめたほうがいいんだろうけど、
誤差の最大値と正負がわからないです。教えてください。

**Comment by takasumiu** [comment]
Scaleを100000とかにしたときに直ったんだったよね確か
