### ISSUE TITLE
ProcessfulObjectのリファクタリング

### ISSUE THREAD

**Issue by takasumiu** [takasumiu/HackTheWorld#57]
dtの受け渡しをもうちょっときれいにしたい。
そのうち。

**Comment by YudaiH** [comment]
コンストラクタに
public ProcessfulObject() : base(500, 300, 100, 100)
という数字が最初から埋め込まれているのは直してほしいです。

**Comment by takasumiu** [comment]
@YudaiH 対応しました

**Comment by takasumiu** [comment]
EditableObjectに改名しました

**Comment by takasumiu** [comment]
すぐに変更を反映させると困る人がいそうなのでmasterはまだ変えてないけど、developブランチをpullすれば見られます。

**Comment by takasumiu** [comment]
とりあえずはよさそう
