### ISSUE TITLE
Playerの重力・ジャンプ処理の整理

### ISSUE THREAD

**Issue by YudaiH** [takasumiu/HackTheWorld#63]
onGround の使用法
乗り判定
天井判定
重力の値
ジャンプの強さ
などがプロトタイプのまま

**Comment by YudaiH** [comment]
乗り判定→GameObjectにいれてほしい
天井判定(＝乗られ判定)→GameObjectにいれてほしい(RiddenByと使用法は異なれど中身は同じ)
重力の値→みんなできめよう
ジャンプの強さ→何段目までジャンプしたいかによって値が定められる。重力が決まれば(ほぼ)自動的に決まる。

**Comment by takasumiu** [comment]
#86 にまとめる
