### ISSUE TITLE
プレイヤーが乗っているEditableブロックが移動したときについていかないことがある

### ISSUE THREAD

**Issue by takasumiu** [takasumiu/HackTheWorld#76]
ブロック.VY = 4
とかならついていくけど

毎フレーム
ブロック.Y += 4
にはついていかない問題をどうするか

解決策
1. Processに変換時に「ブロック.Y += 4」のようなコードはVYを使ったものに変換してもらう
2. SceneのUpdateで前のフレームの位置を保存しておいて、移動していたら追随させる

**Comment by takasumiu** [comment]
ちょっとこっちで調整したい感あるから、ブロック動くverのも早めにpullreq出してくれると助かる

**Comment by YudaiH** [comment]
Processの問題とBlock-Player間の問題が重なった、二重の問題となっています。
切りわけて考えたいです。

**Comment by YudaiH** [comment]
暫定的に対応できている形になっていますね。ありがとうございます。

**Comment by takasumiu** [comment]
#106 と重複
