### ISSUE TITLE
イラスト付ける

### ISSUE THREAD

**Issue by takasumiu** [takasumiu/HackTheWorld#78]
- フリーソフトから持ってくる
  - 棒人間
  - [ピクトグラム](http://pictogram2.com/)
- 自分たちで頑張って描く
    - ドット絵
- Ingress みたいに図形だけでそれっぽく見せる

サイバー空間？

**Comment by YudaiH** [comment]
サイズの大きい画像はJPGで、小さいもの乃至透過が必要なものはPNGで作ってください。

**Comment by takasumiu** [comment]
写真ならともかくイラスト素材は全部pngがいいと思う

**Comment by takasumiu** [comment]
山手とジョンが作ってくれてる
Gravity みたいなシンプルな感じ

**Comment by takasumiu** [comment]
プレイヤー以外そろってる
