### ISSUE TITLE
動くオブジェクト(Player、EditableObjects)が消える

### ISSUE THREAD

**Issue by YudaiH** [takasumiu/HackTheWorld#81]
原因不明。わかり次第対処します。

**Comment by YudaiH** [comment]
座標か速度が急におかしくなって枠外へ移動するようである。

**Comment by YudaiH** [comment]
原因が全く分からないので対処ができないです。情報をお願いします。

**Comment by YudaiH** [comment]
報告です。EditableEnemyも消えることが発覚しました。

**Comment by YudaiH** [comment]
ただしEditableEnemyは一定の位置で消えているからプログラムの仕様なのかも。
float-int間の計算ミスなのでしょうか。

**Comment by takasumiu** [comment]
しばらく様子を見て消えなければ Close

**Comment by takasumiu** [comment]
問題なさそう
