### ISSUE TITLE
ステージエディタを作る？

### ISSUE THREAD

**Issue by takasumiu** [takasumiu/HackTheWorld#95]

**Comment by YudaiH** [comment]
エディタの目的は何ですか？　開発者のため？
エディタの仕様はどうですか？

**Comment by takasumiu** [comment]
目的はステージづくりを楽にするため
ゲームを作るだけならともかくある程度のクオリティを目指すと後半はバランス調整との戦いになると思う。
そのときに楽にステージを作って試せる環境があるかどうかはかなりその作業の大変さを左右すると思う。

仕様はまだ未定だけど、ゲーム本体の側でステージのデータ構造決めてからじゃないと決められない。
ステージの構造は今日明日で決めるつもり。

**Comment by takasumiu** [comment]
- リアルタイムに反映
- 書きやすさ

**Comment by takasumiu** [comment]
Block, Enemy, Item があるステージは作れるようになった

**Comment by takasumiu** [comment]
とりあえず出来てはいるので〆
ただしステージエディタの改良を別イシューで
